package bg.svetozar.tastypizza.service;

import bg.svetozar.tastypizza.model.entity.Translation;
import bg.svetozar.tastypizza.repository.TranslationRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
@Transactional
public class TranslationService {

    private final TranslationRepository translationRepository;

    public Translation saveOrUpdateTranslation(
            String entityType,
            Long entityId,
            String fieldName,
            String language,
            String translatedText,
            boolean autoGenerated
    ) {
        Translation translation = translationRepository
                .findByEntityTypeAndEntityIdAndFieldNameAndLanguage(entityType, entityId, fieldName, language)
                .orElseGet(() -> Translation.builder()
                        .entityType(entityType)
                        .entityId(entityId)
                        .fieldName(fieldName)
                        .language(language)
                        .createdAt(LocalDateTime.now())
                        .build());

        translation.setTranslatedText(translatedText);
        translation.setAutoGenerated(autoGenerated);

        return translationRepository.save(translation);
    }

    @Transactional(readOnly = true)
    public String getTranslationOrDefault(
            String entityType,
            Long entityId,
            String fieldName,
            String language,
            String defaultText
    ) {
        return translationRepository
                .findByEntityTypeAndEntityIdAndFieldNameAndLanguage(entityType, entityId, fieldName, language)
                .map(Translation::getTranslatedText)
                .orElse(defaultText);
    }

    @Transactional(readOnly = true)
    public List<Translation> getTranslationsForEntity(String entityType, Long entityId) {
        return translationRepository.findAllByEntityTypeAndEntityId(entityType, entityId);
    }
}
