package bg.svetozar.tastypizza.controller;

import bg.svetozar.tastypizza.model.dto.translation.TranslationPreviewRequest;
import bg.svetozar.tastypizza.model.dto.translation.TranslationPreviewResponse;
import bg.svetozar.tastypizza.model.dto.translation.EntityTranslationsResponse;
import bg.svetozar.tastypizza.model.dto.translation.TranslationValueDto;
import bg.svetozar.tastypizza.service.TranslationService;
import bg.svetozar.tastypizza.service.TranslationPreviewService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.LinkedHashMap;
import java.util.Map;

@RestController
@RequestMapping("/api/admin/translations")
@RequiredArgsConstructor
@PreAuthorize("hasRole('ADMIN')")
public class AdminTranslationController {

    private final TranslationPreviewService translationPreviewService;
    private final TranslationService translationService;

    @PostMapping("/preview")
    public TranslationPreviewResponse preview(
            @Valid @RequestBody TranslationPreviewRequest request
    ) {
        return translationPreviewService.preview(request);
    }

    @GetMapping("/{entityType}/{entityId}")
    public EntityTranslationsResponse getForEntity(
            @PathVariable String entityType,
            @PathVariable Long entityId
    ) {
        Map<String, Map<String, TranslationValueDto>> fields = new LinkedHashMap<>();

        translationService.getTranslationsForEntity(entityType, entityId)
                .forEach(translation ->
                        fields.computeIfAbsent(translation.getFieldName(), key -> new LinkedHashMap<>())
                                .put(
                                        translation.getLanguage(),
                                        new TranslationValueDto(
                                                translation.getTranslatedText(),
                                                translation.isAutoGenerated()
                                        )
                                )
                );

        return new EntityTranslationsResponse(entityType, entityId, fields);
    }
}
